### ISSUE TITLE
header-nav

### ISSUE THREAD

**Issue by ziven27** [ziven27/tutorial#10]
## logo
![-1](https://cloud.githubusercontent.com/assets/7261176/19119073/2ada0464-8b51-11e6-99b2-947644d7fdd7.png)
```html
<h1 class="g_logo fl">
  <a href="." title="Crafty">
    <img src="../common/img/logo.png" width="71" height="35" alt="Crafty">
  </a>
</h1>
```
```css
.g_header {
	height: 40px;
	line-height: 40px;
	background-color: #353434;
}
.g_logo {
	height: 40px;
	border-right: 1px solid #404040;
	padding-right: 40px;
}
```
我们的图片要居中，需要在header里面添加与高度一样的行高。这样其内部的文字和图片就都垂直居中了。（其实不是完全居中的，是有点偏下的，因为人的眼睛竖着看偏下的东西反而感觉居中）。
>[ 怎么切logo？](https://github.com/ziven27/blog/issues/10)
