### ISSUE TITLE
header-nav

### ISSUE THREAD

**Issue by ziven27** [ziven27/tutorial#11]
![-1](https://cloud.githubusercontent.com/assets/7261176/19120319/025fcb00-8b55-11e6-8b9c-ca503e3d4b0b.png)
```css
.g_nav {
	padding-left: 22px;
}
.g_nav a {
	display: inline-block;
	padding: 0 18px;
	color: #fff;
}
.g_nav a:hover {
	color: #65bf95;
}
```
这里我们可以看到我没有直接采用36像素的右外边距，而是采用了一半的18像素左右内间距。同时我还设定了一个`display: inline-block;`，其实这两个方法都是为了扩大链接的可点击区域。设定了`display: inline-block;`属性之后，链接的上下可点区域一下扩大到了40像素（和行高一样，继承父级header的）。
